<?php $this->headTitle('Delete Administrator');?>
<?php $this->pageHeader = 'Delete Administrator';?>

<?php if($this->allow_delete):?>
  <div class="alert alert-block">
    <h4 class="alert-heading">
      Warning!
    </h4>
    This user will be deleted permanently.<br>
    This action cannot be undone.
  </div>
<?php else:?>
  <div class="alert alert-block alert-error">
    <h4 class="alert-heading">
      Error!
    </h4>
    You cannot delete your own account
  </div>
<?php endif;?>

<div class="form-vertical">
  <div class="control-group">
    <label class="control-label">Username:</label>
    <div class="control">
      <?php echo $this->escape($this->user['username']);?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">Name:</label>
    <div class="control">
      <?php echo $this->escape($this->user['firstname']);?>
      <?php echo $this->escape($this->user['lastname']);?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">Email:</label>
    <div class="control">
      <?php echo $this->escape($this->user['email']);?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">Account Status:</label>
    <div class="control">
      <?php echo ($this->user['active']) ? 'Active' : 'Inactive';?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">Last Login:</label>
    <div class="control">
      <?php echo $this->dateFormat($this->user['last_login'], 'm/d/Y h:i A');?>
    </div>
  </div>
</div>
<?php echo $this->form; ?>
