<?php

/**
 * Test class for Model_Admin.
 * Generated by PHPUnit on 2012-06-02 at 19:28:26.
 */
class Model_AdminTest extends Test_DbTestCase
{

  /**
   * tests Model_Admin::getAdministratorList
   */
  public function testGetAdministratorList() {
    $mgr = new Model_Admin();
    $results = $mgr->getAdministratorList();
    $this->assertInstanceOf('Zend_Paginator', $results);
    $this->assertEquals(1, $results->getTotalItemCount());
  }

  /**
   * tests Model_Admin::addAdministrator
   */
  public function testAddAdministrator() {
    $mgr = new Model_Admin();
    $data = array(
      'username' => 'newusername',
      'password' => 'password',
      'firstname' => 'Firstname',
      'lastname' => 'Lastname',
      'email' => 'newadmin@address.com',
      'active' => '1',
    );
    $id = $mgr->addAdministrator($data);
    $this->assertGreaterThan(0, $id);
  }

  /**
   * tests Model_Admin::updateAdministrator
   */
  public function testUpdateAdministrator() {
    $id = 2;
    $mgr = new Model_Admin();
    $data = array(
      'username' => 'newusername',
      'firstname' => 'newFirstname',
      'lastname' => 'newLastname',
      'email' => 'admin@address.com',
      'active' => '1',
    );
    $updated = $mgr->updateAdministrator($id, $data);
    $this->assertEquals(1, $updated);
  }

  /**
   * tests Model_Admin::deleteAdministrator
   */
  public function testDeleteAdministrator() {
    $id = 2;
    $mgr = new Model_Admin();
    $deleted = $mgr->deleteAdministrator($id);
    $this->assertEquals(1, $deleted);
  }

}

