<?php

/**
 * Test class for Model_User.
 * Generated by PHPUnit on 2012-06-02 at 18:55:19.
 */
class Model_UserTest extends Test_DbTestCase
{

  protected function setUp() {
    parent::setUp();
    Zend_Auth::getInstance()->setStorage(new Zend_Auth_Storage_Session('zfapp_test_auth'));
  }

  protected function tearDown() {
    parent::tearDown();
    if (isset($_SESSION['zfapp_test_auth'])) {
      unset($_SESSION['zfapp_test_auth']);
    }
  }

  /**
   * tests Model_User::getProfile
   */
  public function testGetProfile() {
    $id = 1;
    $mgr = new Model_User();
    $user = $mgr->getProfile($id);
    $this->assertInternalType('array', $user);
  }

  /**
   * tests Model_User::updateProfile
   */
  public function testUpdateProfile() {
    $id = 1;
    $mgr = new Model_User();
    $data = array(
      'username' => 'newusername',
      'firstname' => 'newFirstname',
      'lastname' => 'newLastname',
      'email' => 'email@address.com',
      'active' => '1',
    );
    $updated = $mgr->updateProfile($id, $data);
    $this->assertEquals(1, $updated);
  }

  /**
   * tests Model_User::login
   */
  public function testLogin() {
    $mgr = new Model_User();
    $username = 'username';
    $password = 'password';
    $user = $mgr->login($username, $password);
    $this->assertNotNull($user);
  }

  /**
   * tests Model_User::resetPassword
   */
  public function testResetPassword() {
    $id = 1;
    $mgr = new Model_User();
    $user = $mgr->resetPassword('email@address.com');
    $this->assertInternalType('array', $user);
  }

  /**
   * tests Model_User::changePassword
   */
  public function testChangePassword() {
    $id = 1;
    $mgr = new Model_User();
    $data = array(
      'old_password' => 'password',
      'password' => 'newpassword',
      'confirm_password' => 'newpassword'
    );
    $form = new Form_ChangePassword();
    $form->populate($data);
    $updated = $mgr->changePassword($id, $form);
    $this->assertEquals(1, $updated);
  }

  /**
   * tests Model_User::confirmPasswordReset
   */
  public function testConfirmPasswordReset() {
    $id = 1;
    $mgr = new Model_User();
    $user = $mgr->resetPassword('email@address.com');
    $data = array(
      'password' => 'newpassword',
      'confirm_password' => 'newpassword'
    );
    $form = new Form_ChangePassword();
    $form->removeElement('csrf');
    $form->removeElement('old_password');
    $form->populate($data);
    $user = $mgr->confirmPasswordReset($user['token'], $form);
    $this->assertNotNull($user);
  }

  /**
   * tests Model_User::encryptPassword
   */
  public function testEncryptPassword() {
    $raw = 'password';
    $encrypted = Model_User::encrypt($raw);
    $this->assertNotEquals($raw, $encrypted);
  }

}

