<?php if(!isset($this->params)) $this->params = array(); ?>
<?php if ($this->totalItemCount): ?>

  <div class="pagination">
    <div class="summary">
      Showing Results <?php echo $this->firstItemNumber?> to <?php echo $this->lastItemNumber?> of <?php echo $this->totalItemCount?>
    </div>
    <?php if($this->pageCount > 1):?>
    <ul class="links">

      <!-- First page link -->
        <?php if (isset($this->first) && $this->first < $this->current): ?>
          <li class="first">
            <a href="<?php echo  $this->url(array('page' => $this->first)+$this->params); ?>">&#171; First</a>
          </li>
        <?php else: ?>
          <li class="first disabled">
          <a>&#171; First</a>
        </li>
        <?php endif; ?>
      </li>

      <!-- Previous page link -->
      <?php if (isset($this->previous)): ?>
        <li class="prev">
          <a href="<?php echo $this->url(array('page' => $this->previous)+$this->params); ?>">&larr; Previous</a>
        </li>
      <?php else: ?>
        <li class="prev disabled">
          <a>&larr; Previous</a>
        </li>
      <?php endif; ?>

      <!-- Numbered page links -->
      <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
          <li>
            <a href="<?php echo $this->url(array('page' => $page)+$this->params); ?>">
              <?php echo  $page; ?>
            </a>
          </li>
        <?php else: ?>
           <li class="active">
            <a><?php echo  $page; ?></a>
          </li>
        <?php endif; ?>
      <?php endforeach; ?>

      <!-- Next page link -->
      <?php if (isset($this->next)): ?>
        <li class="next">
          <a href="<?php echo  $this->url(array('page' => $this->next)+$this->params); ?>">Next &rarr;</a>
        </li>
      <?php else: ?>
        <li class="next disabled">
          <a>Next &rarr;</a>
        </li>
      <?php endif; ?>


      <!-- Last page link -->
      <?php if (isset($this->next)): ?>
        <li class="last">
          <a href="<?php echo  $this->url(array('page' => $this->last)+$this->params); ?>">Last &#187;</a>
        </li>
      <?php else: ?>
        <li class="last disabled">
          <a>Last &#187;</a>
        </li>
      <?php endif; ?>

    </ul>
    <?php endif;?>
  </div>
<?php endif; ?>