<?php

/**
 * Test class for Form_Login.
 * Generated by PHPUnit on 2012-06-02 at 17:47:03.
 */
class Form_LoginTest extends PHPUnit_Framework_TestCase
{

  public function testValidation() {
    $form = new Form_Login();
    // Remove csrf token for testing
    $form->removeElement('csrf');
    $data = array(
      'username' => 'username',
      'password' => 'password',
    );
    $valid = $form->isValid($data);
    $this->assertTrue($valid);
  }

  public function testMissingUsername() {
    $form = new Form_Login();
    // Remove csrf token for testing
    $form->removeElement('csrf');
    $data = array(
      'username' => null,
      'password' => 'password',
    );
    $valid = $form->isValid($data);
    $this->assertFalse($valid);
    $errors = $form->getElement('username')->getErrors();
    $this->assertContains('isEmpty', $errors);
  }

  public function testMissingPassword() {
    $form = new Form_Login();
    // Remove csrf token for testing
    $form->removeElement('csrf');
    $data = array(
      'username' => 'username',
      'password' => null,
    );
    $valid = $form->isValid($data);
    $this->assertFalse($valid);
    $errors = $form->getElement('password')->getErrors();
    $this->assertContains('isEmpty', $errors);
  }

}

