<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcontent extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('content', array(
             'id' =>
             array(
              'type' => 'integer',
              'primary' => true,
              'unsigned' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'url' =>
             array(
              'type' => 'string',
              'notblank' => true,
              'notnull' => true,
              'unique' => true,
              'length' => 255,
             ),
             'title' =>
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'content' =>
             array(
              'type' => 'clob',
              'length' => 2147483647,
             ),
             'active' =>
             array(
              'type' => 'boolean',
              'default' => 0,
              'notnull' => true,
              'unsigned' => true,
              'length' => 25,
             ),
             'date_created' =>
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'last_updated' =>
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'can_delete' =>
             array(
              'type' => 'boolean',
              'default' => 1,
              'notnull' => true,
              'unsigned' => true,
              'length' => 25,
             ),
             'edit_url' =>
             array(
              'type' => 'boolean',
              'default' => 1,
              'notnull' => true,
              'unsigned' => true,
              'length' => 25,
             ),
             'full_page' =>
             array(
              'type' => 'boolean',
              'default' => 1,
              'notnull' => true,
              'unsigned' => true,
              'length' => 25,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' =>
             array(
              'routes' =>
              array(
              'fields' =>
              array(
               0 => 'active',
               1 => 'full_page',
              ),
              ),
             ),
             'primary' =>
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('content');
    }
}