<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addadministrator extends Doctrine_Migration_Base
{
    public function up()
    {
        $mgr = new Model_User();
        $mgr->insert(array(
          'username' => 'admin',
          'firstname' => '',
          'lastname' => 'Administrator',
          'email' => 'email@example.com',
          'active' => 1,
          'date_created' => date('Y-m-d H:i:s'),
          'accesslevel' => Model_Admin::ACCESS_SUPERADMIN
        ));
    }

    public function down()
    {
        $mgr = new Model_User();
        $mgr->getAdapter()->query("TRUNCATE `users`");
    }
}