<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcontent extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('content', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'unsigned' => true,
              'autoincrement' => true,
              'comment' => 'Primary key',
              'length' => 4,
             ),
             'url' => 
             array(
              'type' => 'string',
              'notblank' => true,
              'notnull' => true,
              'unique' => true,
              'comment' => 'Url the page can be found at',
              'length' => 255,
             ),
             'title' => 
             array(
              'type' => 'string',
              'comment' => 'Used as the meta title for the page',
              'length' => 255,
             ),
             'content' => 
             array(
              'type' => 'clob',
              'comment' => 'The page content',
              'length' => 2147483647,
             ),
             'meta_title' => 
             array(
              'type' => 'string',
              'comment' => 'Used in the <title> tag',
              'length' => 255,
             ),
             'meta_keywords' => 
             array(
              'type' => 'string',
              'comment' => 'Kewords for SEO <meta> keywords tag',
              'length' => NULL,
             ),
             'meta_description' => 
             array(
              'type' => 'string',
              'comment' => 'Description for SEO <meta> description tag',
              'length' => NULL,
             ),
             'active' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'notnull' => true,
              'unsigned' => true,
              'comment' => 'Only active pages can be accessed',
              'length' => 25,
             ),
             'date_created' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'last_updated' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'can_delete' => 
             array(
              'type' => 'boolean',
              'default' => 1,
              'notnull' => true,
              'unsigned' => true,
              'comment' => 'If 0 this page cannot be deleted.',
              'length' => 25,
             ),
             'edit_url' => 
             array(
              'type' => 'boolean',
              'default' => 1,
              'notnull' => true,
              'unsigned' => true,
              'comment' => 'If 0 the url cannot be changed.',
              'length' => 25,
             ),
             'full_page' => 
             array(
              'type' => 'boolean',
              'default' => 1,
              'notnull' => true,
              'unsigned' => true,
              'comment' => 'If 0 do not create a route for this page.',
              'length' => 25,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
              'routes' => 
              array(
              'fields' => 
              array(
               0 => 'active',
               1 => 'full_page',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('content');
    }
}