<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcontent extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('content', array(
             'id' =>
             array(
              'type' => 'integer',
              'primary' => true,
              'unsigned' => true,
              'autoincrement' => true,
              'length' => 4,
              'comment' => 'Primary key',
             ),
             'url' =>
             array(
              'type' => 'string',
              'notblank' => true,
              'notnull' => true,
              'unique' => true,
              'length' => 255,
              'comment' => 'Url the page can be found at',
             ),
             'title' =>
             array(
              'type' => 'string',
              'length' => 255,
              'comment' => 'Used as the meta title for the page',
             ),
             'content' =>
             array(
              'type' => 'clob',
              'length' => 2147483647,
              'comment' => 'The page content',
             ),
             'active' =>
             array(
              'type' => 'boolean',
              'default' => 0,
              'notnull' => true,
              'unsigned' => true,
              'length' => 25,
              'comment' => 'Only active pages can be accessed',
             ),
             'date_created' =>
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
              'comment' => 'The date the content was created.',
             ),
             'last_updated' =>
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
              'comment' => 'The date the content was last updated.',
             ),
             'can_delete' =>
             array(
              'type' => 'boolean',
              'default' => 1,
              'notnull' => true,
              'unsigned' => true,
              'length' => 25,
              'comment' => 'If 0 this page cannot be deleted.',
             ),
             'edit_url' =>
             array(
              'type' => 'boolean',
              'default' => 1,
              'notnull' => true,
              'unsigned' => true,
              'length' => 25,
              'comment' => 'If 0 the url cannot be changed.',
             ),
             'full_page' =>
             array(
              'type' => 'boolean',
              'default' => 1,
              'notnull' => true,
              'unsigned' => true,
              'length' => 25,
              'comment' => 'If 0 do not create a route for this page.',
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' =>
             array(
              'routes' =>
              array(
              'fields' =>
              array(
               0 => 'active',
               1 => 'full_page',
              ),
              ),
             ),
             'primary' =>
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('content');
    }
}