<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addusers extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('users', array(
             'id' =>
             array(
              'type' => 'integer',
              'primary' => true,
              'unsigned' => true,
              'autoincrement' => true,
              'length' => 4,
              'comment' => 'primary key',
             ),
             'username' =>
             array(
              'type' => 'string',
              'notblank' => true,
              'notnull' => true,
              'unique' => true,
              'length' => 25,
              'comment' => 'The username the user logs in with',
             ),
             'password' =>
             array(
              'type' => 'string',
              'fixed' => 1,
              'notblank' => true,
              'notnull' => true,
              'length' => 128,
              'comment' => 'The password the user logs in with',
             ),
             'firstname' =>
             array(
              'type' => 'string',
              'notblank' => true,
              'notnull' => true,
              'length' => 32,
              'comment' => 'The first name of the user',
             ),
             'lastname' =>
             array(
              'type' => 'string',
              'notblank' => true,
              'notnull' => true,
              'length' => 64,
              'comment' => 'The last name of the user',
             ),
             'email' =>
             array(
              'type' => 'string',
              'notnull' => true,
              'notblank' => true,
              'unique' => true,
              'length' => 127,
              'comment' => 'The email address of the user',
             ),
             'active' =>
             array(
              'type' => 'boolean',
              'default' => 0,
              'notnull' => true,
              'unsigned' => true,
              'length' => 25,
              'comment' => 'Only active users may log in.',
             ),
             'date_created' =>
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
              'comment' => 'The date the user account was created.',
             ),
             'last_login' =>
             array(
              'type' => 'timestamp',
              'length' => 25,
              'comment' => 'The date the user last logged in.',
             ),
             'accesslevel' =>
             array(
              'type' => 'string',
              'notblank' => true,
              'notnull' => true,
              'default' => 'user',
              'length' => 50,
              'comment' => 'The access level of the user',
             ),
             'token' =>
             array(
              'type' => 'string',
              'fixed' => 1,
              'length' => 128,
              'comment' => 'Token used for password reset',
             ),
             'password_key' =>
             array(
              'type' => 'string',
              'fixed' => 1,
              'length' => 128,
              'comment' => 'Hash used for password reset',
             ),
             'token_date' =>
             array(
              'type' => 'date',
              'length' => 25,
              'comment' => 'Date the password reset token expires.',
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' =>
             array(
              'login' =>
              array(
              'fields' =>
              array(
               0 => 'username',
               1 => 'password',
               2 => 'active',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' =>
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('users');
    }
}