<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addmetatags extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('content', 'meta_title', 'string', '255', array(
             'comment' => 'Used in the <title> tag',
             ));
        $this->addColumn('content', 'meta_keywords', 'string', '', array(
             'comment' => 'Kewords for SEO <meta> keywords tag',
             ));
        $this->addColumn('content', 'meta_description', 'string', '', array(
             'comment' => 'Description for SEO <meta> description tag',
             ));
    }

    public function down()
    {
        $this->removeColumn('content', 'meta_title');
        $this->removeColumn('content', 'meta_keywords');
        $this->removeColumn('content', 'meta_description');
    }
}