<?php $this->headTitle('Edit Page');?>
<?php $this->pageHeader = 'Edit Page';?>

<?php $this->headScript()->appendFile($this->baseUrl('/assets/scripts/tiny_mce/tiny_mce.js'), 'text/javascript');?>
<?php $this->placeholder('footerScript')->captureStart();?>
<script type="text/javascript">
tinyMCE.init({
    mode : "exact",
    elements: 'content',
    theme : "advanced",
    plugins : "fullscreen,paste,table,contextmenu,inlinepopups",
    dialog_type : "modal",
    object_resizing : false,
    element_format : "xhtml",
    fix_list_elements : true,
    paste_auto_cleanup_on_paste : true,
    theme_advanced_resizing : true,
    theme_advanced_blockformats: 'p,h1,h2,h3,h4,h5,h6',
    document_base_url : "<?php echo $this->escape($this->site_info['url']);?>",
    theme_advanced_toolbar_location : "top",
    theme_advanced_toolbar_align : "left",
    theme_advanced_statusbar_location : "bottom",
    theme_advanced_link_targets : "_blank=New Window",
    theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,|,outdent,indent,|,cut,copy,pastetext,pasteword,|,undo,redo,|,link,unlink,|,blockquote,image,hr,charmap",
    theme_advanced_buttons2 : "tablecontrols,formatselect,|,forecolor,|,code,fullscreen",
    theme_advanced_buttons3 : ""
});
</script>
<?php $this->placeholder('footerScript')->captureEnd();?>

<?php echo $this->form; ?>