<?php

/**
 * Base_Content
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $url
 * @property string $title
 * @property clob $content
 * @property string $meta_title
 * @property string $meta_keywords
 * @property string $meta_description
 * @property boolean $active
 * @property timestamp $date_created
 * @property timestamp $last_updated
 * @property boolean $can_delete
 * @property boolean $edit_url
 * @property boolean $full_page
 * 
 * @package    App
 * @subpackage Model
 * @author     spekkionu <spekkionu@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Content extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('content');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'comment' => 'Primary key',
             'length' => '4',
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'notnull' => true,
             'unique' => true,
             'comment' => 'Url the page can be found at',
             'length' => '255',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Used as the meta title for the page',
             'length' => '255',
             ));
        $this->hasColumn('content', 'clob', 2147483647, array(
             'type' => 'clob',
             'comment' => 'The page content',
             'length' => '2147483647',
             ));
        $this->hasColumn('meta_title', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Used in the <title> tag',
             'length' => '255',
             ));
        $this->hasColumn('meta_keywords', 'string', null, array(
             'type' => 'string',
             'comment' => 'Kewords for SEO <meta> keywords tag',
             ));
        $this->hasColumn('meta_description', 'string', null, array(
             'type' => 'string',
             'comment' => 'Description for SEO <meta> description tag',
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'notnull' => true,
             'unsigned' => true,
             'comment' => 'Only active pages can be accessed',
             ));
        $this->hasColumn('date_created', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'comment' => 'The date the content was created.',
             ));
        $this->hasColumn('last_updated', 'timestamp', null, array(
             'type' => 'timestamp',
             'comment' => 'The date the content was last updated.',
             ));
        $this->hasColumn('can_delete', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             'notnull' => true,
             'unsigned' => true,
             'comment' => 'If 0 this page cannot be deleted.',
             ));
        $this->hasColumn('edit_url', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             'notnull' => true,
             'unsigned' => true,
             'comment' => 'If 0 the url cannot be changed.',
             ));
        $this->hasColumn('full_page', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             'notnull' => true,
             'unsigned' => true,
             'comment' => 'If 0 do not create a route for this page.',
             ));


        $this->index('routes', array(
             'fields' => 
             array(
              0 => 'active',
              1 => 'full_page',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'date_created',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'name' => 'last_updated',
              'type' => 'timestamp',
             ),
             ));
        $this->actAs($timestampable0);
    }
}