<?php $this->headTitle('My Account');?>
<?php $this->pageHeader = 'My Account';?>

<nav class="page-navigation">
  <ul class="tabs">
    <li class="active"><a href="<?php echo $this->route('admin_account');?>" data-icon="icon-user">My Profile</a></li>
    <li><a href="<?php echo $this->route('admin_account_profile');?>" data-icon="icon-user" class="">Edit Profile</a></li>
    <li><a href="<?php echo $this->route('admin_account_password');?>" data-icon="icon-key" class="">Change Password</a></li>
  </ul>
</nav>

<table class="details-table">
  <tr>
    <th>Username:</th>
    <td><?php echo $this->escape($this->profile['username']);?></td>
  </tr>
  <tr>
    <th>Name:</th>
    <td>
      <?php echo $this->escape($this->profile['firstname']);?>
      <?php echo $this->escape($this->profile['lastname']);?>
    </td>
  </tr>
  <tr>
    <th>Email:</th>
    <td><?php echo $this->escape($this->profile['email']);?></td>
  </tr>
  <tr>
    <th>Last Login:</th>
    <td><?php echo $this->dateFormat($this->profile['last_login'], 'm/d/Y h:i A');?></td>
  </tr>

</table>