<?php

/**
 * Table_Content
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Table_Content extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Table_Content
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Content');
    }

    
}