<?php

/**
 * Table_MigrationVersion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Table_MigrationVersion extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Table_MigrationVersion
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MigrationVersion');
    }
}