<p>A password reset has been requested for the account with email address <?php echo $this->escape($this->user['email']);?></p>

<p>To complete the password reset visit <a href="<?php echo $this->route('admin_save_password', array('token'=>$this->user['token']));?>"><?php echo $this->route('admin_save_password', array('token'=>$this->user['token']));?></a> and enter the PIN below and your desired new password.</p>

<p>PIN: <?php echo $this->escape($this->user['password_key']);?></p>