<?php

/**
 * Test class for Model_Content.
 * Generated by PHPUnit on 2012-06-02 at 15:22:39.
 */
class Model_ContentTest extends Test_DbTestCase
{

  protected function setUp() {
    parent::setUp();
    Cache::clearCacheManager();
  }

  protected function tearDown() {
    parent::tearDown();
  }

  /**
   * tests Model_Content::getPageList
   */
  public function testGetPageList() {
    $mgr = new Model_Content();
    $pages = $mgr->getPageList();
    $this->assertInstanceOf('Zend_Paginator', $pages);
    $this->assertEquals(2, $pages->getTotalItemCount());
  }

  /**
   * tests Model_Content::getPage
   */
  public function testGetPage() {
    $mgr = new Model_Content();
    $page = $mgr->getPage(1);
    $this->assertInternalType('array', $page);
    $this->assertEquals(1, $page['id']);
  }

  /**
   * tests Model_Content::getPageContent
   */
  public function testGetPageContent() {
    $mgr = new Model_Content();
    $page = $mgr->getPageContent(1);
    $this->assertInternalType('array', $page);
    $this->assertEquals(1, $page['id']);
  }

  /**
   * tests Model_Content::addPage
   */
  public function testAddPage() {
    $mgr = new Model_Content();
    $data = array(
      'url' => 'pageurl',
      'title' => 'Page Title',
      'active' => '1',
      'content' => '<p>Page Content</p>'
    );
    $id = $mgr->addPage($data);
    $this->assertGreaterThan(0, $id);
  }

  /**
   * tests Model_Content::updatePage
   */
  public function testUpdatePage() {
    $id = 1;
    $mgr = new Model_Content();
    $data = array(
      'url' => 'pageurl',
      'title' => 'New Title',
      'active' => '1',
      'content' => '<p>Page Content</p>'
    );
    $updated = $mgr->updatePage($id, $data);
    $this->assertEquals(1, $updated);
  }

  /**
   * tests Model_Content::deletePage
   */
  public function testDeletePage() {
    $id = 1;
    $mgr = new Model_Content();
    $deleted = $mgr->deletePage($id);
    $this->assertEquals(1, $deleted);
  }

  /**
   * tests Model_Content::getRoutes
   */
  public function testGetRoutes() {
    $mgr = new Model_Content();
    $routes = $mgr->getRoutes();
    $this->assertInternalType('array', $routes);
    $this->assertContainsOnly('Zend_Controller_Router_Route_Static', $routes);
  }

  /**
   * tests Model_Content::filterUrl
   */
  public function testFilterUrl() {
    $unfiltered = "/path//two-words/";
    $filtered = "path/two-words";
    $path = Model_Content::filterUrl($unfiltered);
    $this->assertEquals($filtered, $path);
  }

  /**
   * tests Model_Content::filterContent
   */
  public function testFilterContent() {
    $unfiltered = "<p>content";
    $filtered = '<p>content</p>';
    $expected = new DOMDocument;
    $expected->loadXML($filtered);
    $path = Model_Content::filterContent($unfiltered);
    $actual = new DOMDocument;
    $actual->loadXML($path);
    $this->assertEqualXMLStructure($expected->firstChild, $actual->firstChild);
  }

}

