<?php

/**
 * Test class for Model_EmailTemplates.
 * Generated by PHPUnit on 2012-06-02 at 18:40:52.
 */
class Model_EmailTemplatesTest extends PHPUnit_Framework_TestCase
{

  /**
   * @var Model_EmailTemplates
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    // Setup Email Template class
    $config['mail'] = array(
      // Can be smtp or sendmail.  This sets the method of sending mails
      'type' => 'sendmail',
      // An email address to use as a force return path.
      'options' => array(
        'forcereturn' => null
      ),
      // SMTP mail settings, ignored if sendmail is used
      'smtp' => array(
        // SMTP Mail Server
        'server' => 'mail.example.com',
        'options' => array(
          // SSL type.  Comment out if no ssl is used. Can be tls or ssl
          'ssl' => 'tls',
          // The port to connect to the mail server with.  Generally 25 for tls and 465 for ssl.
          'port' => 25,
          // Auth type.  Can be plain, login or crammd5.  Comment lines if authentication is not needed.
          'auth' => 'login',
          // Username and password for the given mail account.
          'username' => 'username',
          'password' => 'password'
        )
      ),
      'test' => array(
        // If true all mail will be sent to test address rather than normal target
        'enabled' => false,
        // Array of test addresses
        'address' => array('test@example.com')
      ),
      // Send copies of all emails to these addresses
      'bcc' => array(
        // If true send copy of all mails
        'enabled' => false,
        // Array of test addresses
        'address' => array('test@example.com')
      ),
      // The address to send email from
      'from' => array(
        'email' => 'email@example.com',
        'name' => 'From Name'
      ),
      // Array of email addresses to send application notifications to
      'notify' => array('email@example.com')
    );
    Model_EmailTemplates::setConfig($config['mail']);
    Model_EmailTemplates::setTemplateDir(SYSTEM . '/configs/email_templates');
  }

  /**
   * tests Model_EmailTemplates::getDefaultMailInstance
   */
  public function testGetDefaultMailInstance() {
    $mgr = new Model_EmailTemplates();
    $mail = $mgr->getDefaultMailInstance();
    $this->assertInstanceOf('Zend_Mail', $mail);
  }

}

