<?php echo $this->doctype('HTML5');?>
<html lang="en">
<head>
<?php
$this->headMeta()->setCharset('utf8');
echo $this->headMeta();

$this->headTitle($this->site_info['name'].' Administration', 'PREPEND')->setSeparator(' - ');
echo $this->headTitle();

// CSS Files
$this->headLink()->appendStylesheet($this->baseUrl('assets/vendor/jquery-ui/themes/cupertino/jquery.ui.theme.css'), 'screen');
$this->headLink()->appendStylesheet($this->baseUrl('assets/vendor/bootstrap/docs/assets/css/bootstrap.css'), 'screen');
$this->headLink()->appendStylesheet($this->baseUrl('assets/vendor/bootstrap/docs/assets/css/bootstrap-responsive.css'), 'screen');
//$this->headLink()->appendStylesheet($this->baseUrl('assets/vendor/jquery-validation.password/jquery.validate.password.css'));
$this->headLink()->appendStylesheet($this->baseUrl('assets/styles/admin.css'), 'screen');
//$this->headLink()->appendStylesheet($this->baseUrl('assets/styles/admin.min.css'), 'screen');


$this->headLink()->appendStylesheet($this->baseUrl('assets/styles/ie.css'), 'screen', 'lt IE 8');
echo $this->headLink();

// Javascript Files (These will appear in reverse order)
$this->headScript()->prependFile($this->baseUrl('assets/scripts/admin.js'), 'text/javascript');
//$this->headScript()->prependFile($this->baseUrl('assets/vendor/jquery-validation.password/jquery.validate.password.js'), 'text/javascript');
$this->headScript()->prependFile($this->baseUrl('assets/vendor/jquery.validation/additional-methods.js'), 'text/javascript');
$this->headScript()->prependFile($this->baseUrl('assets/vendor/jquery.validation/jquery.validate.js'), 'text/javascript');
$this->headScript()->prependFile($this->baseUrl('assets/vendor/jquery-form/jquery.form.js'), 'text/javascript');
$this->headScript()->prependFile($this->baseUrl('assets/vendor/jquery-bgiframe/jquery.bgiframe.js'), 'text/javascript');
$this->headScript()->prependFile($this->baseUrl('assets/vendor/jquery.cookie/jquery.cookie.js'), 'text/javascript');
$this->headScript()->prependFile($this->baseUrl('assets/vendor/jquery-metadata/jquery.metadata.js'), 'text/javascript');
$this->headScript()->prependFile($this->baseUrl('assets/vendor/bootbox/bootbox.js'), 'text/javascript');
$this->headScript()->prependFile($this->baseUrl('assets/vendor/bootstrap/js/bootstrap-alert.js'), 'text/javascript');
$this->headScript()->prependFile($this->baseUrl('assets/vendor/bootstrap/js/bootstrap-button.js'), 'text/javascript');
$this->headScript()->prependFile($this->baseUrl('assets/vendor/bootstrap/js/bootstrap-dropdown.js'), 'text/javascript');
$this->headScript()->prependFile($this->baseUrl('assets/vendor/bootstrap/js/bootstrap-collapse.js'), 'text/javascript');
$this->headScript()->prependFile($this->baseUrl('assets/vendor/jquery-ui/ui/jquery-ui.js'), 'text/javascript');
$this->headScript()->prependFile($this->baseUrl('assets/vendor/jquery/jquery.js'), 'text/javascript');
//$this->headScript()->prependFile($this->baseUrl('assets/scripts/admin.min.js'), 'text/javascript');
$this->headScript()->prependFile($this->baseUrl('/assets/vendor/html5shiv-dist/html5shiv.js'), 'text/javascript', array('conditional' => 'if lt IE 9'));

echo $this->headScript();

echo $this->headStyle();
?>
<?php echo $this->placeholder('headExtra'); ?>
</head>
<body>
  <div class="container-fluid">
    <header class="main-header">
      <nav class="main-navigation clearfix">
        <div class="topbar-wrapper" style="z-index: 5;">
          <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
              <div class="container-fluid">
                <a href="<?php echo $this->route('admin_home');?>" class="brand"><?php echo $this->escape($this->site_info['name']);?> Administration</a>
                <?php echo $this->navigation()->menu()->setUlClass('nav')->renderMenu(null, array('maxDepth'=>0)) ?>
                <?php if($this->hasAccess('admin','general')):?>
                  <ul class="nav pull-right">
                    <li class="dropdown">
                      <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                        <?php echo $this->escape($this->identity->username);?>
                        <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                        <li><a href="<?php echo $this->route('admin_account');?>" title="Manage account profile">My Account</a></li>
                        <li><a href="<?php echo $this->route('admin_logout');?>" title="Log out">Log Out</a></li>
                      </ul>
                    </li>
                  </ul>
                <?php endif;?>
              </div>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <section class="content-container">
      <header class="page-header">
        <?php if($this->pageHeader):?>
          <h1 class="page-title"><?php echo $this->escape($this->pageHeader);?></h1>
        <?php endif;?>
        <?php if($this->url() != $this->route('admin_home')):?>
        <ul class="breadcrumb">
          <li><a href="<?php echo $this->route('admin_home');?>" title="Admin Dashboard">Dashboard</a> <span class="divider">/</span></li>
          <?php $this->navigation()->findOneByRoute('admin_login')->setVisible(true); ?>
            <?php $this->navigation()->findOneByRoute('admin_account')->setVisible(true); ?>
          <li><?php echo $this->navigation()->breadcrumbs()->setLinkLast(FALSE)->setMinDepth(0)->setSeparator('</li><span class="divider">/</span><li>'); ?></li>
        </ul>
        <?php endif;?>
        <?php echo $this->flashMessages();?>
      </header>
      <div class="maincontent">
        <?php echo $this->layout()->content;?>
      </div>
    </section>
    <footer class="site-footer">
      &copy; copyright 2012 <a href="#" target="_blank">spekkionu</a>
    </footer>
  </div>
  <?php echo $this->placeholder('footerScript'); ?>
</body>
</html>