<?php


/**
 * Test class for Crypt.
 * Generated by PHPUnit on 2011-12-15 at 10:29:02.
 */
class CryptTest extends PHPUnit_Framework_TestCase
{

  /**
   * @var Crypt
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new Crypt;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testSetKey().
   */
  public function testSetKey() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testSetAlgorithm().
   */
  public function testSetAlgorithm() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testEncrypt().
   */
  public function testEncrypt() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers {className}::{origMethodName}
   * @todo Implement testDecrypt().
   */
  public function testDecrypt() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

}

?>
