<?php echo $this->doctype('HTML5');?>
<html lang="en">
<head>
<?php
$this->headMeta()->setCharset('utf-8');
echo $this->headMeta();

$this->headTitle('My App')->setSeparator(' - ');
echo $this->headTitle();

$this->headLink()->appendStylesheet($this->baseUrl('assets/styles/bootstrap/css/bootstrap.min.css'), 'screen');
$this->headLink()->appendStylesheet($this->baseUrl('assets/styles/bootstrap/css/bootstrap-responsive.min.css'), 'screen');
$this->headLink()->appendStylesheet($this->baseUrl('assets/styles/styles.css'), 'screen');
echo $this->headLink();

$this->headScript()->appendFile('assets/vendor/html5shiv-dist/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9'));
echo $this->headScript();

echo $this->headStyle();
?>
</head>
<body>
<h1>Default</h1>
<?php echo $this->layout()->content;?>
</body>
</html>