<?php $this->headTitle('My Account');?>
<?php $this->pageHeader = 'My Account';?>

<nav class="page-navigation">
  <ul class="nav nav-tabs">
    <li class="active"><a href="<?php echo $this->route('admin_account');?>">My Profile</a></li>
    <li><a href="<?php echo $this->route('admin_account_profile');?>">Edit Profile</a></li>
    <li><a href="<?php echo $this->route('admin_account_password');?>">Change Password</a></li>
  </ul>
</nav>

<table class="table details-table">
  <tr>
    <th>Username:</th>
    <td><?php echo $this->escape($this->profile['username']);?></td>
  </tr>
  <tr>
    <th>Name:</th>
    <td>
      <?php echo $this->escape($this->profile['firstname']);?>
      <?php echo $this->escape($this->profile['lastname']);?>
    </td>
  </tr>
  <tr>
    <th>Email:</th>
    <td><?php echo $this->escape($this->profile['email']);?></td>
  </tr>
  <tr>
    <th>Last Login:</th>
    <td><?php echo $this->dateFormat($this->profile['last_login'], 'm/d/Y h:i A');?></td>
  </tr>

</table>