<?php $this->headTitle('Change Password');?>
<?php $this->pageHeader = 'Change Password';?>

<nav class="page-navigation">
  <ul class="nav nav-tabs">
    <li><a href="<?php echo $this->route('admin_account');?>">My Profile</a></li>
    <li><a href="<?php echo $this->route('admin_account_profile');?>">Edit Profile</a></li>
    <li class="active"><a href="<?php echo $this->route('admin_account_password');?>">Change Password</a></li>
  </ul>
</nav>

<?php echo $this->form;?>